CREATE DATABASE IF NOT EXISTS job;
CREATE DATABASE IF NOT EXISTS company;
CREATE DATABASE IF NOT EXISTS review;

GRANT ALL PRIVILEGES ON job.* TO 'balraj'@'%';
GRANT ALL PRIVILEGES ON company.* TO 'balraj'@'%';
GRANT ALL PRIVILEGES ON review.* TO 'balraj'@'%';

FLUSH PRIVILEGES;